# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.19.5'

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(z.size)
print(z.itemsize)
print("Total Memory size of array is",z.size*z.itemsize)

10
8
Total Memory size of array is 80


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
z = np.zeros(10)
z[4]= 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
z = np.arange(10,50)
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
z = np.arange(9)
z = z.reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
z = np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
z = np.random.random((3,3,3))
print(z)

[[[0.02614839 0.97651283 0.54874042]
  [0.70910407 0.42540251 0.90062341]
  [0.78990985 0.5941045  0.40921853]]

 [[0.30577332 0.36431831 0.14651154]
  [0.6591699  0.31297723 0.83072582]
  [0.72108249 0.46391935 0.29695774]]

 [[0.22091724 0.29855269 0.58278689]
  [0.54553181 0.98897181 0.8408333 ]
  [0.47062117 0.8460412  0.60608087]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
z = np.random.random((10,10))
zmin, zmax = z.min(), z.max()
print(zmin, zmax)

0.001712221380670731 0.977922785673975


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
z = np.random.random(30)
m = z.mean()
print(m)

0.5195120902329043


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
z = np.ones((10,10))
z[1:-1,1:-1]=0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
z = np.diag(1+np.arange(4), k = -1)
print(z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
z = np.zeros ((8,8), dtype=int)
z[1::2, ::2]= 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
array= np.array([[0,1], [1,0]])
z = np.tile(array,(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
z = np.random.random((5,5))
zmax, zmin = z.max(), z.min()
z = (z-zmin)/(zmax-zmin)
print(z)

[[0.50569254 0.31306351 0.46416604 0.87841648 0.92484397]
 [0.90109713 0.96221661 0.79552098 0.37215317 0.51133249]
 [0.21065577 0.18503822 0.31416736 0.1762271  0.        ]
 [0.424867   0.95707457 0.30328028 0.95508183 1.        ]
 [0.8189272  0.80967783 0.86543727 0.94016333 0.43095032]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.arange(15).reshape((5, 3))
y = np.arange(6).reshape((3, 2))
np.dot(x, y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(11)
x[(x >= 3) & (x <= 8)] = -1
print(x)

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.arange(3)
z**z       # = [0^0, 1^1, 2^2] = [1, 1, 4]
2 << z >> 2  # = [0, 1, 2]
z < - z      # = [False, False, False]
1j * z       # = [0 + 0.j, 0 + 1.j, 0 + 2.j]
z/1/1    # = [0, 1, 2]
z<z>z    # ValueError

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10, +10, 10)
np.copysign(np.ceil(np.abs(x)), x)

array([ 7., -9., -2., 10., -1., -4.,  9.,  8.,  1., -2.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.arange(0, 10)
y = np.arange(5, 15)
np.intersect1d(x, y)

array([5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
z = np.ones(1) / 0
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-12-28
Today:  2021-12-29
Tomorrow:  2021-12-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2
C = np.ones(3) * 3
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
z = np.random.uniform(0,10,10)
print(z - z%1)
print(np.floor(z))
print(np.ceil(z)-1)
print(z.astype(int))
print(np.trunc(z))

[1. 1. 2. 2. 7. 7. 5. 7. 7. 8.]
[1. 1. 2. 2. 7. 7. 5. 7. 7. 8.]
[1. 1. 2. 2. 7. 7. 5. 7. 7. 8.]
[1 1 2 2 7 7 5 7 7 8]
[1. 1. 2. 2. 7. 7. 5. 7. 7. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
z = np.zeros((5,5))
z += np.arange(5)
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate_integers():
    for i in range(10):
        yield i
np.fromiter(generate_integers(), dtype=np.float32, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
z = np.linspace(0,1,12,endpoint=True)[1:-1]

print(z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(size=10)
x.sort()

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
z = np.arange(10)

np.add.reduce(z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
z = np.zeros(10)

z.flags.writeable = False

z[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
z = np.random.random((10,2))

X,Y = z[:,0], z[:,1]

R = np.sqrt(X**2+Y**2)

T = np.arctan2(Y,X)

print(R)

print(T)

[1.36730811 0.71117613 0.76569203 0.61946266 0.94331991 1.02072832
 0.64778113 0.5623081  0.407125   1.17795161]
[0.79115051 1.18843465 1.41587256 1.51603687 0.40638384 0.96550445
 1.04862894 1.50724306 1.47717412 0.98520765]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
z = np.random.random(10)

z[z.argmax()] = 0

print(z)

[0.55700343 0.38648587 0.57705782 0.80034513 0.33336009 0.82406474
 0.1285075  0.         0.89448529 0.16894895]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5,5), [('x',float),('y',float)])

z['x'], z['y'] = np.meshgrid(np.linspace(0,1,5),

np.linspace(0,1,5))

print(z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)

Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)

print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:

  print(np.iinfo(dtype).min)

  print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:

  print(np.finfo(dtype).min)

  print(np.finfo(dtype).max)

  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
z = np.zeros((40,40))
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

94


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
z = np.random.random((10,2))
X,Y = np.atleast_2d(z[:,0], z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)
import scipy
import scipy.spatial
z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(z,z)
print(D)

[[0.         0.71658647 0.45736925 0.52246039 0.74286491 0.45119143
  0.81390245 0.13976128 0.84495952 0.35542311]
 [0.71658647 0.         1.04567492 1.01496259 0.67523897 0.8438157
  0.205752   0.78645122 0.68239163 0.58547993]
 [0.45736925 1.04567492 0.         0.14666914 0.72216758 0.27245559
  1.19397468 0.54148928 0.83825848 0.81274658]
 [0.52246039 1.01496259 0.14666914 0.         0.60627164 0.17876314
  1.18064641 0.63015908 0.72022042 0.8689396 ]
 [0.74286491 0.67523897 0.72216758 0.60627164 0.         0.45030158
  0.88053243 0.88095795 0.11653957 0.92394891]
 [0.45119143 0.8438157  0.27245559 0.17876314 0.45030158 0.
  1.0166345  0.58101774 0.56665645 0.76745376]
 [0.81390245 0.205752   1.19397468 1.18064641 0.88053243 1.0166345
  0.         0.85312645 0.88742598 0.59170389]
 [0.13976128 0.78645122 0.54148928 0.63015908 0.88095795 0.58101774
  0.85312645 0.         0.98129224 0.31239329]
 [0.84495952 0.68239163 0.83825848 0.72022042 0.11653957 0.56665645
  0.88742598 0.9812922

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
z = np.arange(10, dtype=np.int32)

z = z.astype(np.float32, copy=False)

print(z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(z):
    print(index, value)
for index in np.ndindex(z.shape):
    print(index, z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
z = np.zeros((n,n))
np.put(z, np.random.choice(range(n*n), p, replace=False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)

Y = X - X.mean(axis=1, keepdims=True)

print(Y)

[[-0.47089988  0.3389833  -0.16434244 -0.37245284  0.40986247  0.06921013
   0.09487702  0.13509025  0.08333134 -0.12365934]
 [ 0.01011919 -0.14789921  0.25321138  0.40184283 -0.31598804  0.51673739
  -0.06438113 -0.1809588  -0.1686705  -0.30401312]
 [ 0.4080958  -0.15196358  0.21483148  0.10719779 -0.42747073  0.24931235
  -0.480071    0.02006867  0.0449972   0.01500201]
 [-0.00868305 -0.39084005 -0.28792229 -0.06140849  0.43005928 -0.30179961
   0.31928086  0.50044486 -0.35097298  0.15184148]
 [ 0.08861398  0.30503512 -0.35116102  0.45716763  0.09403175 -0.19978366
  -0.39763671  0.18802585  0.13705002 -0.32134296]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
z = np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[1 2 9]
 [0 1 7]
 [9 5 6]]
[[0 1 7]
 [1 2 9]
 [9 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
z = np.random.randint(0,3,(3,10))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.4281330459616264


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[4. 4. 3. 2. 2. 3. 2. 3. 3. 4.]
[7. 7. 5. 3. 3. 5. 3. 5. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[53 55 55 47]
 [60 77 81 43]
 [60 61 63 51]]
[[53 55 55 47]
 [60 77 81 43]
 [60 61 63 51]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.51720349 0.45193821 0.4517879  0.58647957 0.37487119 0.49461552
 0.52863843 0.69878564 0.50964614 0.38895205]
0    0.517203
1    0.451938
2    0.451788
3    0.586480
4    0.374871
5    0.494616
6    0.528638
7    0.698786
8    0.509646
9    0.388952
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([0.46510661, 0.69084561, 1.86683702, 0.24570639, 0.69912005])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 20) ( 0, 29) (10, 26) (10, 32) (16, 29) (16, 98) (20, 29) (22, 53)
 (22, 59) (26, 32) (29, 98) (30, 62) (30, 77) (30, 80) (30, 83) (35, 46)
 (35, 74) (46, 74) (52, 53) (52, 78) (53, 59) (53, 78) (62, 83) (65, 75)
 (65, 94) (75, 94) (77, 80) (83, 83) (83, 85)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.77042644,  0.5837461 ,  0.58175465,  0.93059519,  0.49359834,
        0.67360083, -0.0977118 , -0.48093438, -0.86346295,  0.116406  ,
        0.31510241, -0.48509446, -0.73499181, -0.05811887, -0.85120862,
       -0.92042354,  0.18533275,  0.85483859, -0.10120826,  0.65289117,
       -0.93899912,  0.26202559,  0.74135902,  0.84239391,  0.63168704,
       -0.18231431, -0.31399169, -0.90997562,  0.23810214, -0.00118333,
       -0.16266466, -0.65600321,  0.80758145,  0.68296766, -0.54242344,
       -0.92167447, -0.56339637, -0.61632949,  0.3219632 ,  0.55990642,
       -0.86168305,  0.30217912, -0.5911533 , -0.41901799,  0.25892622,
        0.70618222, -0.99723374, -0.88402381, -0.53786439,  0.92314006,
       -0.38131541, -0.67978376,  0.97405269, -0.77346301, -0.88139314,
        0.53079528, -0.32576829,  0.93188463,  0.38942979, -0.39163345,
        0.54544582,  0.08393752, -0.13532698, -0.35395127,  0.60733973,
       -0.3354962 , -0.99879049, -0.76742741,  0.68270269, -0.62

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 7.05208138 10.86803337  2.04249924  1.4017405   0.73039256  8.61780989
  3.60895463  6.45357707 10.11230988  5.08688633]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 0.97735728  8.96563922 10.42777582  4.18632729  6.50494672 14.64508429
   4.27527692  0.25487407  8.04839167  2.74519239]
 [ 2.70893359  6.35018816 11.42565654  5.7288196  10.89668677 10.26245626
   1.91916967  5.39955578 10.12418583  1.49300115]
 [ 0.92967539  6.0381779   5.42204429  0.97876635  1.37049638 13.56415717
   9.5967296   4.42687245  2.76909172  1.47897759]
 [ 6.40936157  3.19177455 10.55819519  5.25874521 12.79821375  6.26459398
   1.76791213  8.0782995  10.05741086  5.43388701]
 [ 9.25958677  0.82171062  4.3458552   1.0903921   6.82661493  4.37638819
   8.2180635   2.76878364  3.62724218  7.53926146]
 [ 1.84584747  9.76351499 10.82987089  4.51101243  6.32490268 15.54073602
   4.07566692  0.10985399  8.29244566  3.63681844]
 [ 7.70042498  0.12786639  2.47739173  3.30474708  3.02906867  6.54081919
  10.92775351  1.33067846  1.08513976  5.50402608]
 [ 2.64799879  4.33928012  4.20460829  2.07674641  1.16085783 11.88273192
  10.49135006  4.26628305  1.80083783  0.21434767]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[9 3 5 3 1 8 2 7 8 8]
 [4 3 2 9 0 6 0 3 7 1]
 [7 2 1 2 5 3 6 4 1 8]
 [7 7 3 5 1 6 7 9 3 3]
 [8 2 7 4 2 3 0 9 9 6]
 [1 4 4 5 2 9 1 9 1 4]
 [7 5 6 2 0 7 2 8 9 8]
 [9 3 6 3 6 2 6 9 3 1]
 [3 1 9 2 9 4 5 7 6 0]
 [5 3 8 8 4 3 5 5 4 0]]
[[0 0 0 0 0]
 [0 9 3 5 3]
 [0 4 3 2 9]
 [0 7 2 1 2]
 [0 7 7 3 5]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 0 4]
   [1 1 0]
   [2 2 0]]

  [[0 4 1]
   [1 0 1]
   [2 0 3]]

  [[4 1 4]
   [0 1 3]
   [0 3 3]]

  [[1 4 4]
   [1 3 0]
   [3 3 0]]

  [[4 4 1]
   [3 0 3]
   [3 0 1]]

  [[4 1 3]
   [0 3 2]
   [0 1 3]]

  [[1 3 4]
   [3 2 3]
   [1 3 0]]

  [[3 4 3]
   [2 3 4]
   [3 0 2]]]


 [[[1 1 0]
   [2 2 0]
   [1 2 1]]

  [[1 0 1]
   [2 0 3]
   [2 1 3]]

  [[0 1 3]
   [0 3 3]
   [1 3 4]]

  [[1 3 0]
   [3 3 0]
   [3 4 3]]

  [[3 0 3]
   [3 0 1]
   [4 3 1]]

  [[0 3 2]
   [0 1 3]
   [3 1 2]]

  [[3 2 3]
   [1 3 0]
   [1 2 3]]

  [[2 3 4]
   [3 0 2]
   [2 3 1]]]


 [[[2 2 0]
   [1 2 1]
   [4 2 3]]

  [[2 0 3]
   [2 1 3]
   [2 3 4]]

  [[0 3 3]
   [1 3 4]
   [3 4 4]]

  [[3 3 0]
   [3 4 3]
   [4 4 1]]

  [[3 0 1]
   [4 3 1]
   [4 1 0]]

  [[0 1 3]
   [3 1 2]
   [1 0 4]]

  [[1 3 0]
   [1 2 3]
   [0 4 3]]

  [[3 0 2]
   [2 3 1]
   [4 3 2]]]


 [[[1 2 1]
   [4 2 3]
   [1 3 4]]

  [[2 1 3]
   [2 3 4]
   [3 4 3]]

  [[1 3 4]
   [3 4 4]
   [4 3 3]]

  [[3 4 3]
   [4 4 1]
   [3 3 1]]

  [[4 3 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  4 17 12  4]
 [ 4  5  9  7  6]
 [17  9  9 42  9]
 [12  7 42  2  9]
 [ 4  6  9  9  0]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))

k = 4

S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),

np.arange(0, Z.shape[1], k), axis=1)

print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
  N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +

  Z[1:-1,0:-2] + Z[1:-1,2:] +

  Z[2: ,0:-2] + Z[2: ,1:-1] + Z[2: ,2:])


  birth = (N==3) & (Z[1:-1,1:-1]==0)

  survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)

  Z[...] = 0

  Z[1:-1,1:-1][birth | survive] = 1

  return Z

Z = np.random.randint(0,2,(50,50))

for i in range(100): 
  
  Z = iterate(Z)
  print(Z)

Streaming output truncated to the last 5000 lines.
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 1 1 0 0 1 0 0 0]
 [0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)

np.random.shuffle(Z)

n = 5


print (Z[np.argsort(Z)[-n:]])


print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.76 s per loop
10 loops, best of 5: 149 ms per loop
10 loops, best of 5: 124 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[0 4 2]
 [1 3 1]
 [4 4 0]
 [3 0 3]
 [1 1 2]
 [4 1 0]
 [0 1 2]
 [0 4 0]
 [2 1 1]
 [4 2 4]]
[[0 4 2]
 [1 3 1]
 [4 4 0]
 [3 0 3]
 [1 1 2]
 [4 1 0]
 [0 1 2]
 [0 4 0]
 [2 1 1]
 [4 2 4]]
[[0 4 2]
 [1 3 1]
 [4 4 0]
 [3 0 3]
 [1 1 2]
 [4 1 0]
 [0 1 2]
 [0 4 0]
 [2 1 1]
 [4 2 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)    

array([[0.08177175, 0.08127048, 0.67801295, 0.81564681, 0.07374577,
        0.87945594, 0.27526807, 0.50595426, 0.56401898, 0.03989128],
       [0.07399856, 0.07354494, 0.6135613 , 0.73811174, 0.06673553,
        0.7958552 , 0.2491012 , 0.45785845, 0.51040356, 0.03609923],
       [0.04745869, 0.04716776, 0.39350512, 0.47338505, 0.04280057,
        0.51041859, 0.15976007, 0.29364571, 0.3273453 , 0.0231521 ],
       [0.08094554, 0.08044933, 0.67116238, 0.8074056 , 0.07300065,
        0.87057001, 0.27248679, 0.50084215, 0.55832019, 0.03948822],
       [0.00247661, 0.00246143, 0.02053489, 0.02470339, 0.00223353,
        0.02663596, 0.00833701, 0.01532377, 0.01708237, 0.00120818],
       [0.05826671, 0.05790953, 0.4831202 , 0.58119163, 0.05254777,
        0.62665902, 0.19614311, 0.36051926, 0.40189345, 0.02842465],
       [0.05718507, 0.05683452, 0.4741517 , 0.57040256, 0.05157229,
        0.61502591, 0.19250196, 0.35382668, 0.39443282, 0.02789699],
       [0.07862976, 0.07814775, 0.6519610

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)      
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) 
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.09781542  0.24971385]
